name: Build and Replace S3 Bucket Content

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        type: string
        options:
        - prod

env:
  DEPLOY_ENV: ${{ github.event.inputs.environment || 'dev' }}

jobs:
  build-and-replace-s3-content:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'dev' }}
    env:
     BUCKET_NAME: ${{ vars.BUCKET_NAME }}

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install NPM dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Deploying application to Amazon S3
        uses: dvelasquez/deploy-s3-action@main
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-west-2'
          AWS_BUCKET_NAME: ${{ env.BUCKET_NAME }}
          DIST_LOCATION_CODE: ./dist

      - name: Create CloudFront Invalidation
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region us-east-1

          aws cloudfront create-invalidation --distribution-id E2JF6US0D91X7O --paths "/*"

      - name: Tag version
        uses: tvdias/github-tagger@v0.0.1
        with:
          repo-token: ${{ secrets.ACCESS_TOKEN }}
          tag: ${{ env.DEPLOY_ENV }}-${{ github.run_id }}
